// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.30.2
// source: editor/annotations.proto

package annotations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Messages tagged with this will not be processed
	Ignore bool `protobuf:"varint,3001,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Messages tagged with this will have all fields marked as "required":
	AllFieldsRequired bool `protobuf:"varint,3002,opt,name=all_fields_required,json=allFieldsRequired,proto3" json:"all_fields_required,omitempty"`
	// Messages tagged with this will additionally accept null values for all properties:
	AllowNullValues bool `protobuf:"varint,3003,opt,name=allow_null_values,json=allowNullValues,proto3" json:"allow_null_values,omitempty"`
	// Messages tagged with this will have all fields marked as not allowing additional properties:
	DisallowAdditionalProperties bool `protobuf:"varint,3004,opt,name=disallow_additional_properties,json=disallowAdditionalProperties,proto3" json:"disallow_additional_properties,omitempty"`
	// Messages tagged with this will have all nested enums encoded to use constants instead of simple types (supports value annotations):
	EnumsAsConstants bool `protobuf:"varint,3005,opt,name=enums_as_constants,json=enumsAsConstants,proto3" json:"enums_as_constants,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_editor_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_editor_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_editor_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *MessageOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

func (x *MessageOptions) GetAllFieldsRequired() bool {
	if x != nil {
		return x.AllFieldsRequired
	}
	return false
}

func (x *MessageOptions) GetAllowNullValues() bool {
	if x != nil {
		return x.AllowNullValues
	}
	return false
}

func (x *MessageOptions) GetDisallowAdditionalProperties() bool {
	if x != nil {
		return x.DisallowAdditionalProperties
	}
	return false
}

func (x *MessageOptions) GetEnumsAsConstants() bool {
	if x != nil {
		return x.EnumsAsConstants
	}
	return false
}

type EnumOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enums tagged with this will have be encoded to use constants instead of simple types (supports value annotations):
	EnumsAsConstants bool `protobuf:"varint,3001,opt,name=enums_as_constants,json=enumsAsConstants,proto3" json:"enums_as_constants,omitempty"`
	// Enums tagged with this will only provide string values as options (not their numerical equivalents):
	EnumsAsStringsOnly bool `protobuf:"varint,3002,opt,name=enums_as_strings_only,json=enumsAsStringsOnly,proto3" json:"enums_as_strings_only,omitempty"`
	// Enums tagged with this will have enum name prefix removed from values:
	EnumsTrimPrefix bool `protobuf:"varint,3003,opt,name=enums_trim_prefix,json=enumsTrimPrefix,proto3" json:"enums_trim_prefix,omitempty"`
	// Enums tagged with this will not be processed
	Ignore        bool `protobuf:"varint,3004,opt,name=ignore,proto3" json:"ignore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumOptions) Reset() {
	*x = EnumOptions{}
	mi := &file_editor_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOptions) ProtoMessage() {}

func (x *EnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_editor_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOptions.ProtoReflect.Descriptor instead.
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return file_editor_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *EnumOptions) GetEnumsAsConstants() bool {
	if x != nil {
		return x.EnumsAsConstants
	}
	return false
}

func (x *EnumOptions) GetEnumsAsStringsOnly() bool {
	if x != nil {
		return x.EnumsAsStringsOnly
	}
	return false
}

func (x *EnumOptions) GetEnumsTrimPrefix() bool {
	if x != nil {
		return x.EnumsTrimPrefix
	}
	return false
}

func (x *EnumOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fields tagged with this will be omitted from generated schemas
	Ignore bool `protobuf:"varint,3001,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Fields tagged with this will be marked as "required" in generated schemas
	Required bool `protobuf:"varint,3002,opt,name=required,proto3" json:"required,omitempty"`
	// Fields tagged with this will be flattened in generated schemas
	Expanded bool `protobuf:"varint,3007,opt,name=expanded,proto3" json:"expanded,omitempty"`
	// Fields tagged with this will constrain strings using the "minLength" keyword in generated schemas
	MinLength int32 `protobuf:"varint,3003,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	// Fields tagged with this will constrain strings using the "maxLength" keyword in generated schemas
	MaxLength int32 `protobuf:"varint,3004,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	// Fields tagged with this will constrain strings using the "pattern" keyword in generated schemas
	Pattern string `protobuf:"bytes,3005,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// Fields tagged with this will use the specified display name in generated schemas
	DisplayName string `protobuf:"bytes,3006,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Fields tagged with this will use the specified format in generated schemas
	Format string `protobuf:"bytes,3008,opt,name=format,proto3" json:"format,omitempty"`
	// Fields tagged with this will be enabled if the specified expression is true
	Enable        string `protobuf:"bytes,3009,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_editor_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_editor_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_editor_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *FieldOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

func (x *FieldOptions) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldOptions) GetExpanded() bool {
	if x != nil {
		return x.Expanded
	}
	return false
}

func (x *FieldOptions) GetMinLength() int32 {
	if x != nil {
		return x.MinLength
	}
	return 0
}

func (x *FieldOptions) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *FieldOptions) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *FieldOptions) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *FieldOptions) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *FieldOptions) GetEnable() string {
	if x != nil {
		return x.Enable
	}
	return ""
}

type FileOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Files tagged with this will not be processed
	Ignore bool `protobuf:"varint,3001,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Override the default file extension for schemas generated from this file
	Extension     string `protobuf:"bytes,3002,opt,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_editor_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_editor_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_editor_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *FileOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

func (x *FileOptions) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

type OneofOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Required      bool                   `protobuf:"varint,3001,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofOptions) Reset() {
	*x = OneofOptions{}
	mi := &file_editor_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofOptions) ProtoMessage() {}

func (x *OneofOptions) ProtoReflect() protoreflect.Message {
	mi := &file_editor_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofOptions.ProtoReflect.Descriptor instead.
func (*OneofOptions) Descriptor() ([]byte, []int) {
	return file_editor_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *OneofOptions) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

var file_editor_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         3001,
		Name:          "editor.message",
		Tag:           "bytes,3001,opt,name=message",
		Filename:      "editor/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*EnumOptions)(nil),
		Field:         3001,
		Name:          "editor.enum",
		Tag:           "bytes,3001,opt,name=enum",
		Filename:      "editor/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         3001,
		Name:          "editor.field",
		Tag:           "bytes,3001,opt,name=field",
		Filename:      "editor/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         3001,
		Name:          "editor.file",
		Tag:           "bytes,3001,opt,name=file",
		Filename:      "editor/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*OneofOptions)(nil),
		Field:         3001,
		Name:          "editor.oneof",
		Tag:           "bytes,3001,opt,name=oneof",
		Filename:      "editor/annotations.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional editor.MessageOptions message = 3001;
	E_Message = &file_editor_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional editor.EnumOptions enum = 3001;
	E_Enum = &file_editor_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional editor.FieldOptions field = 3001;
	E_Field = &file_editor_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional editor.FileOptions file = 3001;
	E_File = &file_editor_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional editor.OneofOptions oneof = 3001;
	E_Oneof = &file_editor_annotations_proto_extTypes[4]
)

var File_editor_annotations_proto protoreflect.FileDescriptor

const file_editor_annotations_proto_rawDesc = "" +
	"\n" +
	"\x18editor/annotations.proto\x12\x06editor\x1a google/protobuf/descriptor.proto\"\xfd\x01\n" +
	"\x0eMessageOptions\x12\x17\n" +
	"\x06ignore\x18\xb9\x17 \x01(\bR\x06ignore\x12/\n" +
	"\x13all_fields_required\x18\xba\x17 \x01(\bR\x11allFieldsRequired\x12+\n" +
	"\x11allow_null_values\x18\xbb\x17 \x01(\bR\x0fallowNullValues\x12E\n" +
	"\x1edisallow_additional_properties\x18\xbc\x17 \x01(\bR\x1cdisallowAdditionalProperties\x12-\n" +
	"\x12enums_as_constants\x18\xbd\x17 \x01(\bR\x10enumsAsConstants\"\xb6\x01\n" +
	"\vEnumOptions\x12-\n" +
	"\x12enums_as_constants\x18\xb9\x17 \x01(\bR\x10enumsAsConstants\x122\n" +
	"\x15enums_as_strings_only\x18\xba\x17 \x01(\bR\x12enumsAsStringsOnly\x12+\n" +
	"\x11enums_trim_prefix\x18\xbb\x17 \x01(\bR\x0fenumsTrimPrefix\x12\x17\n" +
	"\x06ignore\x18\xbc\x17 \x01(\bR\x06ignore\"\x92\x02\n" +
	"\fFieldOptions\x12\x17\n" +
	"\x06ignore\x18\xb9\x17 \x01(\bR\x06ignore\x12\x1b\n" +
	"\brequired\x18\xba\x17 \x01(\bR\brequired\x12\x1b\n" +
	"\bexpanded\x18\xbf\x17 \x01(\bR\bexpanded\x12\x1e\n" +
	"\n" +
	"min_length\x18\xbb\x17 \x01(\x05R\tminLength\x12\x1e\n" +
	"\n" +
	"max_length\x18\xbc\x17 \x01(\x05R\tmaxLength\x12\x19\n" +
	"\apattern\x18\xbd\x17 \x01(\tR\apattern\x12\"\n" +
	"\fdisplay_name\x18\xbe\x17 \x01(\tR\vdisplayName\x12\x17\n" +
	"\x06format\x18\xc0\x17 \x01(\tR\x06format\x12\x17\n" +
	"\x06enable\x18\xc1\x17 \x01(\tR\x06enable\"E\n" +
	"\vFileOptions\x12\x17\n" +
	"\x06ignore\x18\xb9\x17 \x01(\bR\x06ignore\x12\x1d\n" +
	"\textension\x18\xba\x17 \x01(\tR\textension\"+\n" +
	"\fOneofOptions\x12\x1b\n" +
	"\brequired\x18\xb9\x17 \x01(\bR\brequired:R\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xb9\x17 \x01(\v2\x16.editor.MessageOptionsR\amessage:F\n" +
	"\x04enum\x12\x1c.google.protobuf.EnumOptions\x18\xb9\x17 \x01(\v2\x13.editor.EnumOptionsR\x04enum:J\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xb9\x17 \x01(\v2\x14.editor.FieldOptionsR\x05field:F\n" +
	"\x04file\x12\x1c.google.protobuf.FileOptions\x18\xb9\x17 \x01(\v2\x13.editor.FileOptionsR\x04file:J\n" +
	"\x05oneof\x12\x1d.google.protobuf.OneofOptions\x18\xb9\x17 \x01(\v2\x14.editor.OneofOptionsR\x05oneofB>Z<github.com/xjasonli/protoc-gen-jsonschema/editor/annotationsb\x06proto3"

var (
	file_editor_annotations_proto_rawDescOnce sync.Once
	file_editor_annotations_proto_rawDescData []byte
)

func file_editor_annotations_proto_rawDescGZIP() []byte {
	file_editor_annotations_proto_rawDescOnce.Do(func() {
		file_editor_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_editor_annotations_proto_rawDesc), len(file_editor_annotations_proto_rawDesc)))
	})
	return file_editor_annotations_proto_rawDescData
}

var file_editor_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_editor_annotations_proto_goTypes = []any{
	(*MessageOptions)(nil),              // 0: editor.MessageOptions
	(*EnumOptions)(nil),                 // 1: editor.EnumOptions
	(*FieldOptions)(nil),                // 2: editor.FieldOptions
	(*FileOptions)(nil),                 // 3: editor.FileOptions
	(*OneofOptions)(nil),                // 4: editor.OneofOptions
	(*descriptorpb.MessageOptions)(nil), // 5: google.protobuf.MessageOptions
	(*descriptorpb.EnumOptions)(nil),    // 6: google.protobuf.EnumOptions
	(*descriptorpb.FieldOptions)(nil),   // 7: google.protobuf.FieldOptions
	(*descriptorpb.FileOptions)(nil),    // 8: google.protobuf.FileOptions
	(*descriptorpb.OneofOptions)(nil),   // 9: google.protobuf.OneofOptions
}
var file_editor_annotations_proto_depIdxs = []int32{
	5,  // 0: editor.message:extendee -> google.protobuf.MessageOptions
	6,  // 1: editor.enum:extendee -> google.protobuf.EnumOptions
	7,  // 2: editor.field:extendee -> google.protobuf.FieldOptions
	8,  // 3: editor.file:extendee -> google.protobuf.FileOptions
	9,  // 4: editor.oneof:extendee -> google.protobuf.OneofOptions
	0,  // 5: editor.message:type_name -> editor.MessageOptions
	1,  // 6: editor.enum:type_name -> editor.EnumOptions
	2,  // 7: editor.field:type_name -> editor.FieldOptions
	3,  // 8: editor.file:type_name -> editor.FileOptions
	4,  // 9: editor.oneof:type_name -> editor.OneofOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	5,  // [5:10] is the sub-list for extension type_name
	0,  // [0:5] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_editor_annotations_proto_init() }
func file_editor_annotations_proto_init() {
	if File_editor_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_editor_annotations_proto_rawDesc), len(file_editor_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_editor_annotations_proto_goTypes,
		DependencyIndexes: file_editor_annotations_proto_depIdxs,
		MessageInfos:      file_editor_annotations_proto_msgTypes,
		ExtensionInfos:    file_editor_annotations_proto_extTypes,
	}.Build()
	File_editor_annotations_proto = out.File
	file_editor_annotations_proto_goTypes = nil
	file_editor_annotations_proto_depIdxs = nil
}
